### ISSUE TITLE
main.js line10 大小写错了

### ISSUE THREAD

**Issue by pepesi** [huashuaipeng/shopping#1]

**Comment by huashuaipeng** [comment]
？？？

**Comment by pepesi** [comment]
ubuntu16.04下报错
ERROR in ./src/main.js
Module not found: Error: Can't resolve './components/pageload.vue' in '/home/ppc/vuejs/shopping/src'
 @ ./src/main.js 14:0-49
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

pageload.vue 的名字错了

**Comment by huashuaipeng** [comment]
ok,我知道了，谢谢，欢迎继续指证
